export { default as Affix } from 'antd/es/affix';
export { default as Anchor } from 'antd/es/anchor';
export { default as AutoComplete } from 'antd/es/auto-complete';
export { default as Alert } from 'antd/es/alert';
export { default as Avatar } from 'antd/es/avatar';
export { default as BackTop } from 'antd/es/back-top';
export { default as Badge } from 'antd/es/badge';
export { default as Breadcrumb } from 'antd/es/breadcrumb';
// export { default as Button } from 'antd/es/button';
export { default as Calendar } from 'antd/es/calendar';
export { default as Card } from 'antd/es/card';
export { default as Collapse } from 'antd/es/collapse';
export { default as Carousel } from 'antd/es/carousel';
export { default as Cascader } from 'antd/es/cascader';
export { default as Checkbox } from 'antd/es/checkbox';
export { default as Col } from 'antd/es/col';
export { default as Comment } from 'antd/es/comment';
export { default as ConfigProvider } from 'antd/es/config-provider';
export { default as DatePicker } from 'antd/es/date-picker';
export { default as Descriptions } from 'antd/es/descriptions';
export { default as Divider } from 'antd/es/divider';
export { default as Dropdown } from 'antd/es/dropdown';
export { default as Drawer } from 'antd/es/drawer';
// export { default as Empty } from 'antd/es/empty';
export { default as AntForm } from 'antd/es/form';
export { default as Form } from './form';
// export { default as Image } from 'antd/es/image';
export { default as Input } from 'antd/es/input';
export { default as InputNumber } from 'antd/es/input-number';
export { default as Layout } from 'antd/es/layout';
export { default as List } from 'antd/es/list';
export { default as LocaleProvider } from 'antd/es/locale-provider';
export { default as message } from 'antd/es/message';
export { default as Menu } from 'antd/es/menu';
export { default as Mentions } from 'antd/es/mentions';
export { default as AntModal } from 'antd/es/modal';
// export { default as Modal } from 'antd/es/modal';
export { default as Statistic } from 'antd/es/statistic';
// export { default as antNotification } from 'antd/es/notification';
export { default as PageHeader } from 'antd/es/page-header';
export { default as Popconfirm } from 'antd/es/popconfirm';
export { default as Popover } from 'antd/es/popover';
export { default as Progress } from 'antd/es/progress';
export { default as Radio } from 'antd/es/radio';
export { default as Rate } from 'antd/es/rate';
export { default as Result } from 'antd/es/result';
export { default as Row } from 'antd/es/row';
export { default as AntSelect } from 'antd/es/select';
export { default as Skeleton } from 'antd/es/skeleton';
export { default as Slider } from 'antd/es/slider';
export { default as Space } from 'antd/es/space';
export { default as Spin } from 'antd/es/spin';
export { default as Segmented } from 'antd/es/segmented';
export { default as Steps } from 'antd/es/steps';
export { default as Switch } from 'antd/es/switch';
export { default as Table } from 'antd/es/table';
export { default as Transfer } from 'antd/es/transfer';
export { default as Tree } from 'antd/es/tree';
export { default as AntTreeSelect } from 'antd/es/tree-select';
// export { default as Tabs } from 'antd/es/tabs';
// export { default as Tag } from 'antd/es/tag';
export { default as TimePicker } from 'antd/es/time-picker';
export { default as Timeline } from 'antd/es/timeline';
// export { default as Tooltip } from 'antd/es/tooltip';
export { default as Typography } from 'antd/es/typography';
export { default as Mention } from 'antd/es/mentions';
export { default as Upload } from 'antd/es/upload';
export { default as version } from 'antd/es/version';
/* custom components */
// export { default as Input } from './input';
export { default as Tag } from './tag';
export { default as Select } from './select';
export { default as Pagination } from './pagination';
export { default as HighlightText } from './highlight-text';
export { default as Tooltip } from './tooltip';
export { default as Empty } from './empty';
export { default as Image } from './image';
export { default as Button } from './button';
export { default as Modal } from './modal';
export { default as notification } from './notification';
export { default as Tabs } from './tabs';


